### ISSUE TITLE
Is Railcraft support possible at the moment?

### ISSUE THREAD

**Issue by maleksware** [liachmodded/talk#17]
@liach

Hello, I'm Alex, a young programmer and student.

As I saw in the Railcraft project page, you were a contributor of that project, but now you don't do anything there. There are lots of issues and PRs there, and I think that it'll be cool to check them out.

And my question is: do you plan to continue supporting the Railcraft mod or this is its last stable release that won't be supervised/supported? If you dropped the project, please say so I can fork it and continue the support.

Thank you!

**Comment by liach** [comment]
Hello asmaksimov2007,
Glad that you asked!

Railcraft is driven by interests from contributors. Unfortunately, but most of the Railcraft contributors are dormant. I am not actively supporting it now due to me lacking a strong incentive; same might be for the leader of Railcraft, CovertJaguar, or he may just be busy in his real life, which comes first before online interests.

By the license, CovertJaguar has the exclusive right to release Railcraft builds.

For forking the project, you can do so, but you cannot distribute the built mod per the license. I suggest contacting CovertJaguar through his email (on his GitHub profile) for Railcraft maintenance/forking questions.

**Comment by maleksware** [comment]
Thanks a lot for your answer! I will contact CovertJaguar if i don't get the answer on the Railcraft discord.
